integration works now, but logging is giving us lots of warnings

diff --git a/joern-cli/src/universal/ghidra2cpg b/joern-cli/src/universal/ghidra2cpg
--- a/joern-cli/src/universal/ghidra2cpg
+++ b/joern-cli/src/universal/ghidra2cpg
@@ -8,12 +8,11 @@ fi
 SCRIPT_ABS_DIR=$(dirname "$SCRIPT_ABS_PATH")
 SCRIPT="$SCRIPT_ABS_DIR"/bin/fuzzyc-2-cpg
 
-echo $SCRIPT
 # joern-cli/ghidra2cpg/target/universal/stage/bin/ghidra2cpg
 
-# if [ ! -f "$SCRIPT" ]; then
-#     echo "Unable to find $SCRIPT, have you created the distribution?"
-#     exit 1
-# fi
+if [ ! -f "$SCRIPT" ]; then
+    echo "Unable to find $SCRIPT, have you created the distribution?"
+    exit 1
+fi
 
-# $SCRIPT -J-XX:+UseG1GC -J-XX:CompressedClassSpaceSize=128m "$@"
+$SCRIPT -J-Dlog4j.configurationFile=conf/log4j-ghidra.xml "$@"
