Clarify usage of cpg-create script with joern-server.
- Fix minor issue with launcher scripts using `sh` even though the scripts contain bash extensions. The scripts now run with `bash` rather than `sh`.

diff --git a/joern-cli/src/universal/joern b/joern-cli/src/universal/joern
--- a/joern-cli/src/universal/joern
+++ b/joern-cli/src/universal/joern
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 if [[ $OSTYPE == darwin* ]]; then
     SCRIPT_ABS_PATH=$(greadlink -f "$0")
@@ -9,8 +9,9 @@ SCRIPT_ABS_DIR=$(dirname "$SCRIPT_ABS_PATH")
 SCRIPT="$SCRIPT_ABS_DIR"/bin/ammonite-bridge
 
 if [ ! -f "$SCRIPT" ]; then
-    echo "Unable to find $SCRIPT, have you created the distribution?";
-    exit 1;
-fi;
+    echo "Unable to find $SCRIPT, have you created the distribution?"
+    exit 1
+fi
 
-$SCRIPT -J-XX:+UseG1GC -J-XX:CompressedClassSpaceSize=128m -J-XX:+UseStringDeduplication "$@";
+$SCRIPT -J-XX:+UseG1GC -J-XX:CompressedClassSpaceSize=128m -J-XX:+UseStringDeduplication "$@"
+
